"""Task-scoped function-calling tools for the Job Discovery Agent."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from langchain_core.tools import BaseTool, StructuredTool

from career_agent.jobs.discovery_service import JobDiscoveryService
from career_agent.jobs.search_models import SearchCriteria, SearchResultSelector


@dataclass(frozen=True, slots=True)
class JobDiscoveryToolContext:
    """Trusted context captured by tool closures, never generated by the LLM."""

    tenant_id: str
    thread_id: str
    user_query: str
    max_results: int = 10


def build_job_discovery_tools(
    *,
    service: JobDiscoveryService,
    context: JobDiscoveryToolContext,
) -> tuple[BaseTool, BaseTool]:
    """Build per-turn tools whose arguments are pure user-intent schemas."""

    async def search_jobs(**arguments: Any) -> str:
        criteria = SearchCriteria.model_validate(arguments)
        result = await service.search_and_publish(
            tenant_id=context.tenant_id,
            thread_id=context.thread_id,
            user_query=context.user_query,
            criteria=criteria,
            max_results=context.max_results,
        )
        return result.model_dump_json()

    async def get_job_detail(**arguments: Any) -> str:
        selector = SearchResultSelector.model_validate(arguments)
        result = await service.resolve_and_get_detail(
            tenant_id=context.tenant_id,
            thread_id=context.thread_id,
            selector=selector,
        )
        return result.model_dump_json()

    search_tool = StructuredTool.from_function(
        coroutine=search_jobs,
        name="career_search_jobs",
        description=(
            "Search grounded job postings from explicit user criteria and "
            "publish one numbered result list. Do not invent unstated filters."
        ),
        args_schema=SearchCriteria,
    )
    detail_tool = StructuredTool.from_function(
        coroutine=get_job_detail,
        name="career_get_job_detail",
        description=(
            "Resolve a follow-up reference to the latest displayed job list "
            "and fetch full JD only when exactly one posting matches. "
            "Returns ambiguous or not_found instead of choosing arbitrarily."
        ),
        args_schema=SearchResultSelector,
    )
    return search_tool, detail_tool
