"""The public HTTP/SSE contract, exported for the web client to test against.

The stream events and read responses are a two-sided contract: the backend has
exhaustive renderer tests for what it emits, and the web client has parsers and
TypeScript interfaces for what it consumes. Until now nothing tied the two
together, and the sides drifted twice without a test going red (a transcript
field renamed ``resource`` → ``resources``; an interaction scope added on one
side only). This module renders one deterministic document from the pydantic
models — JSON Schema plus examples built from the real classes — that is
committed under ``web/src/contracts/`` and read by both test suites.

Regenerate with::

    uv run python -m career_agent.api.public_contract

``tests/api/test_public_contract.py`` fails when the committed file is stale.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal, get_args, get_origin

from pydantic import BaseModel, TypeAdapter

from career_agent.agent.job_analysis_contracts import (
    JobAnalysisResult,
    QuotedFinding,
    TieredRequirement,
)
from career_agent.agent.main_agent_contracts import (
    BehaviorPolicyContext,
    OwnerSettingsContext,
    UserPreferencesContext,
)
from career_agent.agent.questionnaire_contracts import QuestionAnswer, QuestionOption, UserQuestion
from career_agent.api.app import (
    BrowserJobCaptureResponse,
    ChatStreamRequest,
    JobCapturedEventAckResponse,
    JobCaptureRetryResponse,
    JobCapturedEventView,
    JobCapturedEventsResponse,
    JobClosureResponse,
    OwnerSettingsHistoryResponse,
    OwnerSettingsResponse,
)
from career_agent.api.integrations import (
    ConnectionResponse,
    DisconnectionResponse,
    GoogleAuthorizationResponse,
)
from career_agent.api.reads import (
    ActionItemView,
    ApplicationMockInterviewsResponse,
    ApplicationView,
    AvailabilityResponse,
    CalendarAccountView,
    CalendarEventView,
    CalendarWorkspaceResponse,
    CompanyResearchView,
    ConversationDeletionResponse,
    ConversationMessageView,
    ConversationResourceView,
    ConversationTranscriptResponse,
    ConversationView,
    CountResponse,
    DailyBriefResponse,
    DashboardResponse,
    DashboardStats,
    EmailAccountView,
    EmailEventView,
    EmailWorkspaceResponse,
    JobDeletionResponse,
    MockInterviewSessionView,
    PursuitStatusResponse,
    ReportView,
    ResumeImportResponse,
    ResumeView,
    SavedJobDetailView,
    SavedJobSnapshotView,
    SavedJobView,
    JobMatchHistoryResponse,
    ResumeJobMatchView,
    TargetRoleView,
)
from career_agent.harness.streaming import (
    ArtifactReadyEvent,
    CapabilityCompletedEvent,
    CapabilityStartedEvent,
    ClientActionEvent,
    ContentDeltaEvent,
    InteractionOption,
    InteractionRequiredEvent,
    InteractionResponse,
    JobResourceReadyEvent,
    ProgressEvent,
    PublicStreamEvent,
    ReportReadyEvent,
    TurnCompletedEvent,
    TurnFailedEvent,
    TurnInputResource,
    TurnStartedEvent,
    TurnSuspendedEvent,
    capability_confirmation_event,
    resume_analysis_confirmation_event,
)
from career_agent.storage.context import OwnerSettingsEvent

CONTRACT_PATH = (
    Path(__file__).resolve().parents[3] / "web" / "src" / "contracts" / "api-contract.ts"
)

_HEADER = """\
// GENERATED by `uv run python -m career_agent.api.public_contract` — do not edit.
//
// JSON Schema and examples for the public SSE events and HTTP responses, built
// from the backend's pydantic models. Emitted as a TypeScript constant rather
// than a .json module so `as const` keeps every string literal narrow: a JSON
// import widens "assistant" to string, which would make a `satisfies` check
// against `role: "user" | "assistant"` fail for the wrong reason.
//
// tests/api/test_public_contract.py fails when this file is stale.
"""

# A fixed instant so the rendered document is byte-stable across runs.
_AT = datetime(2026, 9, 12, 12, 0, tzinfo=timezone.utc)
_INTERACTION_ID = "interaction_0123456789abcdef0123"


def _literals(model: type[BaseModel], field: str) -> tuple[str, ...]:
    """The closed set a field accepts, read from the model so the examples
    below cannot silently cover a subset of it."""

    annotation = model.model_fields[field].annotation
    # ``Literal[...] | None`` arrives as a Union; find the Literal arm wherever it sits.
    candidates = (annotation, *get_args(annotation))
    literals = [arm for arm in candidates if get_origin(arm) is Literal]
    if not literals:
        raise TypeError(f"{model.__name__}.{field} is not a Literal")
    return tuple(str(value) for value in get_args(literals[0]))


def _stream_event_examples() -> tuple[PublicStreamEvent, ...]:
    """At least one instance per event type and per literal that selects
    client behaviour. The web parser must accept every one of these."""

    events: list[PublicStreamEvent] = [TurnStartedEvent(turn_id="turn-1")]
    for stage in _literals(ProgressEvent, "stage"):
        events.append(ProgressEvent(
            stage=stage,
            message=f"阶段：{stage}",
            **(
                {"step_key": "resume_tailoring", "step_label": "正在起草定制简历"}
                if stage == "running_capability" else {}
            ),
        ))
    for capability in _literals(CapabilityStartedEvent, "capability"):
        events.append(
            CapabilityStartedEvent(capability=capability, message=f"开始 {capability}")
        )
        events.append(
            CapabilityCompletedEvent(
                capability=capability,
                state="example_state",
                message=f"完成 {capability}",
            )
        )
    events.extend(
        (
            # One per interaction kind, then one per scope: the scope decides
            # whether a button sends a bound response, the kind decides which
            # widget renders.
            InteractionRequiredEvent(
                interaction_id=_INTERACTION_ID,
                kind="single_selection",
                prompt="请选择一个岗位。",
                options=(
                    InteractionOption(
                        label="AI 产品经理 · 示例科技",
                        description="北京 · 25-35K",
                        selection_index=1,
                    ),
                    InteractionOption(label="后端工程师 · 示例网络", selection_index=2),
                ),
                allow_free_text=True,
            ),
            InteractionRequiredEvent(
                interaction_id=_INTERACTION_ID,
                kind="multiple_selection",
                prompt="选择要对比的岗位。",
                options=(
                    InteractionOption(label="岗位一", selection_index=1),
                    InteractionOption(label="岗位二", selection_index=2),
                ),
            ),
            InteractionRequiredEvent(
                interaction_id=_INTERACTION_ID,
                kind="confirmation",
                prompt="有新的邮件事件待确认。",
                options=(
                    InteractionOption(value="review", label="查看并确认"),
                    InteractionOption(value="later", label="稍后处理"),
                ),
                allow_free_text=True,
            ),
            InteractionRequiredEvent(
                interaction_id=_INTERACTION_ID,
                kind="free_text",
                prompt="请补充目标城市。",
                allow_free_text=True,
            ),
            InteractionRequiredEvent(
                interaction_id=_INTERACTION_ID,
                kind="approval",
                prompt="是否把这场面试写入 Google 日历？",
                options=(
                    InteractionOption(value="confirm", label="确认执行"),
                    InteractionOption(value="cancel", label="暂不执行"),
                ),
            ),
            InteractionRequiredEvent(
                interaction_id=_INTERACTION_ID,
                kind="file_upload",
                prompt="请上传简历。",
            ),
            InteractionRequiredEvent(
                interaction_id=_INTERACTION_ID,
                kind="questionnaire",
                scope="questionnaire",
                prompt="请一次回答两项信息。",
                questions=(
                    UserQuestion(question_id="q1", prompt="使用哪种数据库？", kind="single",
                                 options=(QuestionOption(value="sqlite", label="SQLite"),)),
                    UserQuestion(question_id="q2", prompt="补充项目背景", kind="free_text"),
                ),
            ),
            resume_analysis_confirmation_event(
                conversation_id="conv-1", analysis_id="analysis-1"
            ),
            capability_confirmation_event(
                conversation_id="conv-1",
                confirmation_id="confirmation-1",
                prompt="示例科技 · AI 产品经理，简历 v2\n你设置了此操作需要确认。是否执行？",
            ),
            ContentDeltaEvent(delta="这是一段带换行的正文。\n\n第二段。"),
            ArtifactReadyEvent(
                artifact_id="artifact-1",
                filename="简历-v2.docx",
                media_type=(
                    "application/vnd.openxmlformats-officedocument."
                    "wordprocessingml.document"
                ),
                byte_size=20480,
            ),
        )
    )
    # Every kind, and separately every delivery status, so neither set's
    # coverage depends on how many values the other happens to have.
    for kind in _literals(ReportReadyEvent, "kind"):
        events.append(
            ReportReadyEvent(
                kind=kind,
                resource_id=f"{kind}-1",
                status_at_delivery=None,
                anchored_by_other_job=None,
            )
        )
    for index, status in enumerate(_literals(ReportReadyEvent, "status_at_delivery")):
        events.append(
            ReportReadyEvent(
                kind="job_research_report",
                resource_id=f"report-{status}",
                status_at_delivery=status,
                anchored_by_other_job=bool(index % 2),
            )
        )
    events.extend(
        (
            JobResourceReadyEvent(
                resource_id="jds-1",
                job_posting_id="job-1",
                title="示例科技｜AI 产品经理",
                description="JD 第 1 版 · BOSS直聘",
            ),
            ClientActionEvent(
                action="open_url",
                url="https://www.zhipin.com/web/geek/job?query=AI",
                label="在 BOSS 直聘打开搜索",
            ),
            ClientActionEvent(
                action="open_url",
                url="https://www.zhipin.com/web/geek/job?query=AI",
                label="在 BOSS 直聘打开搜索",
                capture_intent_id=f"capint_{'0' * 32}",
                capture_intent_expires_at=_AT,
            ),
            TurnSuspendedEvent(turn_id="turn-1", interaction_id=_INTERACTION_ID),
            TurnCompletedEvent(turn_id="turn-1"),
            TurnFailedEvent(
                turn_id="turn-1",
                code="MAIN_AGENT_REJECTED_400",
                message="模型拒绝了这次请求。",
            ),
        )
    )
    return tuple(events)


def _action_item(**overrides: Any) -> ActionItemView:
    values: dict[str, Any] = dict(
        id="action-1",
        action_type="follow_up",
        source_type="application",
        application_id="app-1",
        title="跟进示例科技的投递",
        summary="投递已满 7 天没有回音。",
        due_at=_AT,
        status="open",
        snoozed_until=None,
    )
    values.update(overrides)
    return ActionItemView(**values)


def _saved_job(**overrides: Any) -> SavedJobView:
    values: dict[str, Any] = dict(
        id="job-1",
        title="AI 产品经理",
        company_name="示例科技",
        city="北京",
        salary="25-35K",
        source_name="BOSS直聘",
        source_url="https://www.zhipin.com/job_detail/example.html",
        availability_status="active",
        pursuit_status="open",
        captured_at=_AT,
        last_checked_at=_AT,
        application_status=None,
        analysis_summary="偏产品策略，要求有 AI 落地经验。",
        responsibilities=("负责 AI 产品规划",),
        required_skills=("产品设计", "数据分析"),
        preferred_qualifications=("有大模型应用经验",),
        clarification_questions=(),
        analyzed_at=_AT,
        jd_version=2,
        jd_analysis_status="stale",
        jd_analysis_version=1,
        jd_analysis=JobAnalysisResult(
            core_objective="把大模型能力落到可上线的产品功能中。",
            seniority="mid",
            requirements=(
                TieredRequirement(
                    text="3 年以上产品经验",
                    tier="S",
                    kind="fact",
                    jd_quote="3 年以上互联网产品经验",
                ),
            ),
            core_competencies=("需求抽象",),
            implicit_requirements=(
                QuotedFinding(text="能与算法团队直接对接", jd_quote="与算法同学协作"),
            ),
            ats_keywords=("AI 产品", "大模型"),
            hr_focus=("稳定性",),
            hiring_manager_focus=("落地案例",),
            likely_interview_topics=("需求拆解思路",),
            red_flags=(QuotedFinding(text="工时未说明", jd_quote="能适应快节奏"),),
            information_gaps=("未说明团队规模",),
            summary="偏产品策略，要求有 AI 落地经验。",
        ),
        resume_match_status="ready",
        resume_match_fit="moderate",
        resume_match_at=_AT,
    )
    values.update(overrides)
    return SavedJobView(**values)


def _application(**overrides: Any) -> ApplicationView:
    values: dict[str, Any] = dict(
        id="app-1",
        status="interviewing",
        title="AI 产品经理",
        company_name="示例科技",
        city=None,
        salary=None,
        submitted_at=_AT,
        updated_at=_AT,
    )
    values.update(overrides)
    return ApplicationView(**values)


def _read_examples() -> dict[str, list[BaseModel]]:
    """Instances of every response model, grouped by the model's class name.

    Every nullable field is ``None`` in at least one instance so a client type
    that forgot the ``| null`` fails its structural check;
    ``tests/api/test_public_contract.py`` enforces this against the schema.
    Most models need one instance; a model whose nullable fields are mutually
    exclusive gets a second.
    """

    owner_settings = OwnerSettingsContext(
        revision=3,
        preferences=UserPreferencesContext(boss_search="allowed"),
        behavior_policy=BehaviorPolicyContext(revision=1),
    )
    transcript = ConversationTranscriptResponse(
        messages=(
            ConversationMessageView(
                role="user", content="帮我调研一下示例科技。", created_at=_AT
            ),
            ConversationMessageView(
                role="assistant",
                content="调研完成，两份报告见下方卡片。",
                created_at=_AT,
                # Two references on one message: a turn can store two reports.
                resources=(
                    ConversationResourceView(
                        kind="job_research_report",
                        resource_id="report-1",
                        status_at_delivery="current",
                        anchored_by_other_job=False,
                    ),
                    ConversationResourceView(
                        kind="resume_job_match",
                        resource_id="match-1",
                        status_at_delivery=None,
                        anchored_by_other_job=None,
                    ),
                    ConversationResourceView(
                        kind="saved_job",
                        resource_id="jds-1",
                        title="示例科技｜AI 产品经理",
                        description="JD 第 1 版 · BOSS直聘",
                        available=True,
                    ),
                ),
            ),
        ),
        active_workflow=None,
        phase=None,
        pending_interaction=capability_confirmation_event(
            conversation_id="conv-1",
            confirmation_id="confirmation-1",
            prompt="示例科技 · AI 产品经理，简历 v2\n你设置了此操作需要确认。是否执行？",
        ),
        pending_interaction_body=None,
    )
    examples: list[BaseModel] = [
        DailyBriefResponse(
            timezone="Asia/Shanghai",
            generated_at=_AT,
            overdue=(_action_item(),),
            due_today=(),
            upcoming=(_action_item(id="action-2", application_id=None, due_at=_AT),),
            no_due_date=(_action_item(id="action-3", due_at=None, snoozed_until=_AT),),
        ),
        DashboardResponse(
            stats=DashboardStats(
                saved_jobs=12,
                applications=4,
                interviewing=1,
                offers=0,
                resumes=2,
                research_reports=3,
                calendar_accounts=1,
            ),
            application_statuses={"applied": 3, "interviewing": 1},
            recent_jobs=(_saved_job(),),
            recent_applications=(_application(),),
            next_actions=(_action_item(),),
        ),
        _application(city="北京", salary="25-35K"),
        ApplicationMockInterviewsResponse(
            application_id="app-1",
            title="AI 产品经理",
            company_name="示例科技",
            sessions=(
                MockInterviewSessionView(
                    session_id="mock-1",
                    status="completed",
                    interview_type="behavioral",
                    interview_type_label="行为面",
                    question_count=5,
                    max_primary_questions=5,
                    report_id="mock-report-1",
                    summary="项目深度可以，系统设计偏弱。",
                    created_at=_AT,
                    completed_at=_AT,
                    updated_at=_AT,
                ),
                MockInterviewSessionView(
                    session_id="mock-2",
                    status="active",
                    interview_type="technical",
                    interview_type_label="技术面",
                    question_count=2,
                    max_primary_questions=5,
                    report_id=None,
                    summary=None,
                    conversation_id="conv-1",
                    created_at=_AT,
                    completed_at=None,
                    updated_at=_AT,
                ),
            ),
        ),
        _saved_job(
            city=None,
            salary=None,
            source_url=None,
            pursuit_status="dismissed",
            application_status="applied",
            analysis_summary=None,
            analyzed_at=None,
            jd_version=None,
            jd_analysis_status="none",
            jd_analysis_version=None,
            jd_analysis=None,
            resume_match_status="none",
            resume_match_fit=None,
            resume_match_at=None,
        ),
        SavedJobDetailView(
            id="job-1",
            title="AI 产品经理",
            company_name="示例科技",
            city=None,
            salary=None,
            source_name="BOSS直聘",
            source_url=None,
            availability_status="unknown",
            pursuit_status="open",
            jd_text="岗位职责：……\n任职要求：……",
            jd_version=2,
            captured_at=_AT,
        ),
        SavedJobSnapshotView(
            jd_snapshot_id="jds-1",
            job_posting_id="job-1",
            title="AI 产品经理",
            company_name="示例科技",
            source_name="BOSS直聘",
            source_url=None,
            jd_version=1,
            latest_jd_version=2,
            jd_text="岗位职责：……\n任职要求：……",
            captured_at=_AT,
        ),
        AvailabilityResponse(job_posting_id="job-1", availability_status="closed", changed=True),
        PursuitStatusResponse(job_posting_id="job-1", pursuit_status="dismissed", changed=False),
        JobDeletionResponse(job_posting_id="job-1"),
        CountResponse(count=2),
        ConversationView(
            id="conv-1",
            status="active",
            title="示例科技调研",
            last_message_preview="调研完成，两份报告见下方卡片。",
            message_count=2,
            active_workflow=None,
            phase=None,
            created_at=_AT,
            last_active_at=_AT,
        ),
        transcript,
        # An unknown or empty conversation: no messages and no pending gate.
        ConversationTranscriptResponse(),
        ConversationDeletionResponse(conversation_id="conv-1"),
        ReportView(
            kind="job_research_report",
            resource_id="report-1",
            title="示例科技 · AI 产品经理",
            subtitle="岗位调研 · 2026-09-12",
            body="## 公司概况\n\n……",
            created_at=_AT,
        ),
        JobMatchHistoryResponse(
            items=(ResumeJobMatchView(
                report_id="match-1", job_posting_id="job-1",
                job_title="AI 产品经理", company_name="示例科技",
                jd_snapshot_id="jds-1", jd_version=1, jd_captured_at=_AT,
                jd_available=True, current_jd=False,
                resume_version_id="resume-version-1", resume_id="resume-1",
                resume_name="产品简历", resume_version_number=1,
                resume_created_at=_AT, resume_available=True,
                matcher_version="resume-job-match-v2", created_at=_AT,
                overall_fit="moderate", summary="部分要求仍需补充证据。",
            ),),
            total=1, limit=20, offset=0,
        ),
        JobMatchHistoryResponse(total=0, limit=20, offset=0),
        ReportView(
            kind="resume_job_match", resource_id="legacy-match",
            title="简历与岗位匹配", subtitle="历史匹配", body="## 整体判断\n\n证据不足。",
            created_at=_AT,
            resume_job_match=ResumeJobMatchView(
                report_id="legacy-match", job_posting_id="deleted-job",
                jd_snapshot_id="deleted-snapshot", jd_available=False,
                resume_version_id="deleted-resume-version", resume_available=False,
                matcher_version="legacy", created_at=_AT,
                overall_fit="insufficient_evidence", summary="历史输入已不可访问。",
            ),
        ),
        ResumeView(
            id="resume-1",
            name="产品简历",
            target_role="AI 产品经理",
            status="active",
            latest_version_number=2,
            latest_version_id="resume-version-2",
            version_count=2,
            document_format="docx",
            byte_size=20480,
            updated_at=_AT,
        ),
        ResumeImportResponse(
            resume_id="resume-1",
            resume_version_id="resume-version-2",
            name="产品简历",
            version_number=2,
            document_format="docx",
            byte_size=20480,
        ),
        TargetRoleView(id="role-1", title="AI 产品经理", priority=1, status="active"),
        EmailWorkspaceResponse(
            accounts=(
                EmailAccountView(
                    id="email-account-1",
                    provider="gmail",
                    email_address="me@example.com",
                    status="active",
                    connection_status="needs_reauthorization",
                    needs_reauthorization=True,
                    last_synced_at=None,
                ),
            ),
            events=(
                EmailEventView(
                    id="email-event-1",
                    event_type="interview_invitation",
                    status="pending",
                    summary="示例科技邀请一面。",
                    confidence=0.82,
                    application_id=None,
                    application_title=None,
                    company_name=None,
                    occurred_at=_AT,
                ),
            ),
        ),
        CalendarWorkspaceResponse(
            accounts=(
                CalendarAccountView(
                    id="calendar-account-1",
                    provider="google",
                    email_address="me@example.com",
                    calendar_id="primary",
                    status="active",
                    connection_status="connected",
                    needs_reauthorization=False,
                    updated_at=_AT,
                ),
            ),
            events=(
                CalendarEventView(
                    id="calendar-event-1",
                    interview_round_id="round-1",
                    application_id=None,
                    company_name=None,
                    job_title=None,
                    employer_label=None,
                    sequence_number=None,
                    interview_status=None,
                    scheduled_start=None,
                    scheduled_end=None,
                    timezone=None,
                    interview_format=None,
                    location=None,
                    meeting_url=None,
                    contact_summary=None,
                    sync_status="pending",
                    status="scheduled",
                    external_html_link=None,
                    updated_at=_AT,
                ),
            ),
            month=None,
            timezone="Asia/Shanghai",
        ),
        CompanyResearchView(
            id="research-1",
            company_name="示例科技",
            anchor_job_title="AI 产品经理",
            status="completed",
            focus=None,
            summary="成长期 AI 公司。",
            finding_count=6,
            source_count=4,
            created_at=_AT,
        ),
        GoogleAuthorizationResponse(
            authorization_url="https://accounts.google.com/o/oauth2/v2/auth?client_id=example"
        ),
        ConnectionResponse(account_id="email-account-1"),
        DisconnectionResponse(),
        BrowserJobCaptureResponse(
            job_posting_id="job-1",
            jd_snapshot_id="snapshot-1",
            snapshot_version=1,
            title="AI 产品经理",
            company_name="示例科技",
        ),
        BrowserJobCaptureResponse(
            job_posting_id="job-1",
            jd_snapshot_id="snapshot-1",
            snapshot_version=1,
            title="AI 产品经理",
            company_name="示例科技",
            conversation_id="conv-1",
            capture_event_id=f"jobcap_{'0' * 32}",
            capture_event_created=True,
            continuation_status="pending",
            continuation_reason=None,
        ),
        JobCapturedEventsResponse(
            events=(
                JobCapturedEventView(
                    id=f"jobcap_{'0' * 32}",
                    conversation_id="conv-1",
                    job_posting_id="job-1",
                    jd_snapshot_id="snapshot-1",
                    title="AI 产品经理",
                    company_name="示例科技",
                    created_at=_AT,
                    continuation_status="completed",
                    continuation_turn_id="turn-1",
                ),
                JobCapturedEventView(
                    id=f"jobcap_{'1' * 32}",
                    conversation_id="conv-1",
                    job_posting_id="job-2",
                    jd_snapshot_id="snapshot-2",
                    title="算法工程师",
                    company_name="示例科技",
                    created_at=_AT,
                    continuation_status="pending",
                    continuation_turn_id=None,
                ),
            )
        ),
        JobCapturedEventsResponse(events=()),
        JobCapturedEventAckResponse(event_id=f"jobcap_{'0' * 32}", acknowledged=True),
        JobCaptureRetryResponse(event_id=f"jobcap_{'0' * 32}", retried=True),
        JobClosureResponse(matched=False, job_posting_id=None),
        OwnerSettingsResponse(owner_settings=owner_settings),
        OwnerSettingsHistoryResponse(
            events=(
                OwnerSettingsEvent(
                    event_id=1,
                    user_id="u1",
                    revision=3,
                    policy_revision=1,
                    actor_type="api_key",
                    actor_id="key-1",
                    changed_fields=("preferences.boss_search",),
                    before=OwnerSettingsContext(),
                    after=owner_settings,
                    changed_at=_AT,
                ),
            )
        ),
    ]
    grouped: dict[str, list[BaseModel]] = {}
    for example in examples:
        grouped.setdefault(type(example).__name__, []).append(example)
    return grouped


def _request_examples() -> dict[str, list[BaseModel]]:
    return {
        ChatStreamRequest.__name__: [
            ChatStreamRequest(
                conversation_id="conv-1",
                message="确认执行",
                interaction_response=InteractionResponse(
                    interaction_id=_INTERACTION_ID,
                    scope="capability_confirmation",
                    action="confirm",
                ),
            ),
            ChatStreamRequest(
                conversation_id="conv-1",
                message="我刚在 BOSS 保存了一个岗位，请继续分析。",
                interaction_response=InteractionResponse(
                    interaction_id=_INTERACTION_ID,
                    scope="capability_confirmation",
                    action="confirm",
                ),
                input_resources=(
                    TurnInputResource(kind="jd_snapshot", id="jd-1"),
                ),
            ),
            ChatStreamRequest(
                conversation_id="conv-1",
                message="已提交当前任务问卷回答。",
                interaction_response=InteractionResponse(
                    interaction_id=_INTERACTION_ID,
                    scope="questionnaire",
                    action="submit",
                    answers=(
                        QuestionAnswer(question_id="q1", selected_values=("sqlite",)),
                        QuestionAnswer(question_id="q2", free_text="内部项目"),
                    ),
                ),
            ),
        ],
    }


def _wire(examples: list[BaseModel], *, mode: str) -> dict[str, Any]:
    # Responses are described as the server serialises them, so a field marked
    # ``exclude=True`` (``ContentDeltaEvent.delivery``) stays out of the wire
    # contract; requests are described as the server validates them.
    return {
        "schema": type(examples[0]).model_json_schema(mode=mode),
        "examples": [example.model_dump(mode="json") for example in examples],
    }


def public_contract() -> dict[str, Any]:
    stream_adapter: TypeAdapter[PublicStreamEvent] = TypeAdapter(PublicStreamEvent)
    return {
        "stream_events": {
            "schema": stream_adapter.json_schema(mode="serialization"),
            "examples": [
                stream_adapter.dump_python(event, mode="json")
                for event in _stream_event_examples()
            ],
        },
        "reads": {
            name: _wire(examples, mode="serialization")
            for name, examples in sorted(_read_examples().items())
        },
        "requests": {
            name: _wire(examples, mode="validation")
            for name, examples in sorted(_request_examples().items())
        },
    }


def render_public_contract() -> str:
    body = json.dumps(public_contract(), ensure_ascii=False, indent=2, sort_keys=True)
    return f"{_HEADER}\nexport const API_CONTRACT = {body} as const;\n"


def main(argv: list[str] | None = None) -> int:
    arguments = list(sys.argv[1:] if argv is None else argv)
    target = Path(arguments[0]) if arguments else CONTRACT_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_public_contract(), encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
